name: Generate i18n Locale files

permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      locale:
        description: 'List of locales to sync (separated by comma)'
        required: true

jobs:
  create-locale-files:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Testout
        shell: bash
        run: |
          git checkout -b temp-data
          git push origin temp-data
          git config --global user.email "i18n-action@unifyapps.com"
          git config --global user.name "Gen I18n Action"
          git add .
          git commit -m "Create i18n locale files for data" -q
          gh pr create -B main -H temp-data --title 'Merge something into base_branch' --body 'Created by Github action'
      
